transport: udp
listen_address: 0.0.0.0
listen_port: 9000
serial_baud: 420000
serial_device:
  device_hint: ftdi
  vendor_id: 0x0403
  product_id: 0x6001
raw_mode: false
log_level: info
reconnect_delay_ms: 2000
